TOTAL_CLIENTS = 610
TRAIN_CLIENTS_RATIO = 0.7
VALIDATION_RATIO = 0.2
ROUND_CLIENTS = 128

MINI_BATCH_SIZE = 32
LR = 0.01
INPUT_CHANNELS = 256
HIDDEN_CHANNELS = 256
USER_EMBEDDING_SIZE = 1 

ROUNDS = 10
EPOCHS = 5


INCLUDE_NEIGHBORS = True
NEIGHBORS_THRESHOLD = 2

Delta = 0.05
Lambda = 0.1

# 100k Ratings Dataset
RATINGS_DATAFILE = '../data/ml-latest-small/ratings.csv'
MOVIES_INFO_DATAFILE = '../data/ml-latest-small/movies.csv'

CUDA_VISIBLE_DEVICES=1